---
title: "120_Time_series_modelling"
author: "DHJ"
date: "8 5 2020"
output: html_document
---


## 1. Libraries  
```{r}

# All of tehse packages cn be loaded at once using library(tidyverse). (I just like to be specific.)
library(dplyr)
library(tidyr)
library(purrr)
library(lubridate)
library(ggplot2)
library(forcats)
library(mgcv)
library(nlme)

```


## 2. Data  

### Read data
```{r}

dat_annual <- readRDS("Data/110_dat_annual_season_adjusted.rds") %>%
  mutate(station_id = levels(station_id)[as.numeric(station_id)])  # remove factor 

str(dat_annual)

dat_climate <- readRDS("Data/100_Climate.rds")

station_selection <- readRDS("Data/100_Stations_selection.rds")
station_selection_no3 <- station_selection$trends_1992_2016_no3

```

### Add climate data  
```{r}

dat_climate_wide <- dat_climate %>%
  pivot_wider(names_from = "variable", values_from = "value") %>%
  mutate(station_id = as.character(station_id))

nrow(dat_annual)

dat_annual <- dat_annual %>%
  left_join(dat_climate_wide, by = c("station_id", "year"))

nrow(dat_annual)  # check that row number hasn't changed

```

### Pick data  
```{r}

dat_annual_sel <- dat_annual %>%
  filter(station_id %in% station_selection_no3)

nrow(dat_annual_sel)

```



## 3. Time series analyses with gamm    
For each station separately

### Test with one time series
```{r}

dat_annual_test <- dat_annual_sel %>%
  filter(station_id %in% unique(dat_annual_sel$station_id)[1])

mod <- list(
  gamm(log_NO3_madj ~ s(year, k = 3), 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gamm(log_NO3_madj ~ s(TOTN_dep, k = 3), 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gamm(log_NO3_madj ~ s(pre, k = 3), 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gamm(log_NO3_madj ~ s(tmp, k = 3), 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gamm(log_NO3_madj ~ s(pre, k = 3) + s(tmp, k = 3), 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gamm(log_NO3_madj ~ s(TOTN_dep, k = 3) + s(pre, k = 3), 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gamm(log_NO3_madj ~ s(TOTN_dep, k = 3) + s(tmp, k = 3), 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gamm(log_NO3_madj ~ s(TOTN_dep, k = 3) + s(pre, k = 3) + s(tmp, k = 3), 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gamm(TOTN_dep ~ s(year, k = 3), 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gamm(pre ~ s(year, k = 3), 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gamm(tmp ~ s(year, k = 3), 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test)
  )

anova <- anova(mod[[1]]$lme, 
               mod[[2]]$lme,
               mod[[3]]$lme,
               mod[[4]]$lme,
               mod[[5]]$lme,
               mod[[6]]$lme,
               mod[[7]]$lme,
               mod[[8]]$lme)
anova

model_selected <- which.min(anova$AIC)
summary(mod[[model_selected]]$gam)

aic <- data.frame(Model = 1:8,
                  AIC = anova$AIC,
                  dAIC = anova$AIC - min(anova$AIC))

aic

par(mfrow = c(2,2), mar = c(4,5,2,1))
plot(mod[[1]]$gam)
plot(mod[[2]]$gam)
plot(mod[[3]]$gam)

par(mfrow = c(2,3), mar = c(4,5,2,1))
plot(mod[[5]]$gam)
plot(mod[[6]]$gam)
plot(mod[[7]]$gam)

# X <- plot(mod[[3]]$gam)
# str(X)

```

### All time series with TOC     
Ca 4 minutes  
```{r, cache = TRUE}

run_gamm_analyses <- function(data){
  list(
    gamm(log_NO3_madj ~ s(year, k = 3), 
         correlation = corAR1(form =∼ year),
         data = data),
    gamm(log_NO3_madj ~ s(TOTN_dep, k = 3), 
         correlation = corAR1(form =∼ year),
         data = data),
    gamm(log_NO3_madj ~ s(pre, k = 3), 
         correlation = corAR1(form =∼ year),
         data = data),
    gamm(log_NO3_madj ~ s(tmp, k = 3), 
         correlation = corAR1(form =∼ year),
         data = data),
    gamm(log_NO3_madj ~ s(pre, k = 3) + s(tmp, k = 3), 
         correlation = corAR1(form =∼ year),
         data = data),
    gamm(log_NO3_madj ~ s(TOTN_dep, k = 3) + s(pre, k = 3), 
         correlation = corAR1(form =∼ year),
         data = data),
    gamm(log_NO3_madj ~ s(TOTN_dep, k = 3) + s(tmp, k = 3), 
         correlation = corAR1(form =∼ year),
         data = data),
    gamm(log_NO3_madj ~ s(TOTN_dep, k = 3) + s(pre, k = 3) + s(tmp, k = 3), 
         correlation = corAR1(form =∼ year),
         data = data),
    gamm(TOTN_dep ~ s(year, k = 3), 
         correlation = corAR1(form =∼ year),
         data = data),
    gamm(pre ~ s(year, k = 3), 
         correlation = corAR1(form =∼ year),
         data = data),
    gamm(tmp ~ s(year, k = 3), 
         correlation = corAR1(form =∼ year),
         data = data)
  )
}
# Test
# mod <- run_gamm_analyses(dat_annual_test)

# Safe version
run_gamm_analyses_safe <- safely(run_gamm_analyses)


# Split data
dat_annual_split <- dat_annual_sel %>%
  group_by(station_id) %>%
  group_split()

# Name the split data
names(dat_annual_split) <- dat_annual_split %>% map_chr(~.$station_id[1])

# Run all models  
t0 <- Sys.time()
gamm_model_list <- dat_annual_split %>%
  map(run_gamm_analyses_safe) %>%
  transpose()
Sys.time() - t0  

# Set names for result
names(gamm_model_list$error) <- names(dat_annual_split)
names(gamm_model_list$result) <- names(dat_annual_split)

```
## 4. Time series analyses with gls (linear effects)        
For each station separately

### Test with one time series
```{r}

dat_annual_test <- dat_annual_sel %>%
  filter(station_id %in% unique(dat_annual_sel$station_id)[1])

mod <- list(
  gls(log_NO3_madj ~ year, 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gls(log_NO3_madj ~ TOTN_dep, 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gls(log_NO3_madj ~ pre, 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gls(log_NO3_madj ~ tmp, 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gls(log_NO3_madj ~ pre + tmp, 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gls(log_NO3_madj ~ TOTN_dep + pre, 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gls(log_NO3_madj ~ TOTN_dep + tmp, 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gls(log_NO3_madj ~ TOTN_dep + pre + tmp, 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gls(TOTN_dep ~ year, 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gls(pre ~ year, 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test),
  gls(tmp ~ year, 
            correlation = corAR1(form =∼ year),
            data = dat_annual_test)
  )

anova <- anova(mod[[1]], 
               mod[[2]],
               mod[[3]],
               mod[[4]],
               mod[[5]],
               mod[[6]],
               mod[[7]],
               mod[[8]])
anova

model_selected <- which.min(anova$AIC)
summary(mod[[model_selected]]$gam)

aic <- data.frame(Model = 1:8,
                  AIC = anova$AIC,
                  dAIC = anova$AIC - min(anova$AIC))

aic


```

### All time series with TOC     
Ca 20 seconds    
```{r, cache = TRUE}

run_gls_analyses <- function(data){
  list(
  gls(log_NO3_madj ~ year, 
            correlation = corAR1(form =∼ year),
            data = data),
  gls(log_NO3_madj ~ TOTN_dep, 
            correlation = corAR1(form =∼ year),
            data = data),
  gls(log_NO3_madj ~ pre, 
            correlation = corAR1(form =∼ year),
            data = data),
  gls(log_NO3_madj ~ tmp, 
            correlation = corAR1(form =∼ year),
            data = data),
  gls(log_NO3_madj ~ pre + tmp, 
            correlation = corAR1(form =∼ year),
            data = data),
  gls(log_NO3_madj ~ TOTN_dep + pre, 
            correlation = corAR1(form =∼ year),
            data = data),
  gls(log_NO3_madj ~ TOTN_dep + tmp, 
            correlation = corAR1(form =∼ year),
            data = data),
  gls(log_NO3_madj ~ TOTN_dep + pre + tmp, 
            correlation = corAR1(form =∼ year),
            data = data),
  gls(TOTN_dep ~ year, 
            correlation = corAR1(form =∼ year),
            data = data),
  gls(pre ~ year, 
            correlation = corAR1(form =∼ year),
            data = data),
  gls(tmp ~ year, 
            correlation = corAR1(form =∼ year),
            data = data)
  )
}

# Test
# mod <- run_gls_analyses(dat_annual_test)

# Safe version
run_gls_analyses_safe <- safely(run_gls_analyses)


# Split data
dat_annual_split <- dat_annual_sel %>%
  group_by(station_id) %>%
  group_split()

# Name the split data
names(dat_annual_split) <- dat_annual_split %>% map_chr(~.$station_id[1])

# Run all models  
t0 <- Sys.time()
gls_model_list <- dat_annual_split %>%
  map(run_gls_analyses_safe) %>%
  transpose()
Sys.time() - t0  

# Set names for result
names(gls_model_list$error) <- names(dat_annual_split)
names(gls_model_list$result) <- names(dat_annual_split)

```


## 5. Save
```{r}

saveRDS(dat_annual_sel, "Data/120_dat_annual_sel.rds")
saveRDS(gamm_model_list, "Data/120_ts_model_list.rds")
saveRDS(gls_model_list, "Data/120_ts_model_list_linear.rds")

```


