---
title: "150_Interactive_map"
author: "DHJ"
date: "19 3 2021"
output: html_document
---

```{r packages, results='hide', message=FALSE, warning=FALSE, echo = FALSE}

# All of tehse packages cn be loaded at once using library(tidyverse). (I just like to be specific.)
library(dplyr)
library(tidyr)
library(purrr)
library(lubridate)
library(ggplot2)
library(forcats)
library(mgcv)
library(nlme)

library(MuMIn)
# install.packages("randomForest")
library(randomForest)

library(mapview)
library(leafpop)

library(effects)    # handles lme models  
library(readxl)

knitr::opts_chunk$set(echo = FALSE)

```

### Data 
```{r main_data, echo = FALSE}

dat_annual_sel <- readRDS("Data/120_dat_annual_sel.rds")
ts_model_list <- readRDS("Data/120_ts_model_list_linear.rds")
# ts_model_list_wout_TOC <- readRDS("Data/120_ts_model_list_wout_TOC.rds")

df_stations <- readRDS("Data/100_Stations.rds")
df_deposition <- readRDS("Data/100_Deposition.rds")
df_climate <- readRDS("Data/100_Climate.rds")

```
Number of time series: `r length(ts_model_list$result)`  
Sample size (years x time series): `r nrow(dat_annual_sel)`  
  

```{r metadata, echo = FALSE}

df_station <- read_excel(
  "K:/Prosjekter/langtransporterte forurensninger/O-23300 - ICP-WATERS - HWI/Faglige rapporter/2020 report/Land cover/ICPW_All_Stations_2020_2020_05_04.xlsx") %>%
  mutate(station_id = as.character(station_id))

```


```{r get_result_list, echo = FALSE}
#
# Results of time series analysis of each time series        
#

# Which time series did not retun an error?
model_ok <- ts_model_list$error %>% map_lgl(is.null)
# table(model_ok)

# Length of result: 4 if TOC is not included, 8 if TOC is included
result_length <- ts_model_list$result %>% map_int(length)

# Check contents of $result
# $result[[1]][1:3] %>% str(2)

result_list <- ts_model_list$result[model_ok]


```
Number of time series with results: `r length(result_list)`  

```{r extract_slope_estimates, echo = FALSE}
#
# Extract slope estimates   
#

# Models  
# - model 2: effect of deposition on NO3
# - model 9: time trend in deposition   

# summary(result_list[[1]][[2]]$gam)$r.sq

slope_no3_vs_dep <- result_list %>% 
  map_dbl(~coef(summary(.[[1]]))[2, 1])

slope_dep_vs_time <- result_list %>% 
  map_dbl(~coef(summary(.[[9]]))[2, 1])

slope_1 <- tibble(
  station_id = names(slope_no3_vs_dep),
  slope_no3_vs_dep,
  slope_dep_vs_time
)


# Get column  names
# names(dat_annual_sel) %>% paste(collapse = ", ")

df_meta <- dat_annual_sel %>%
  as_tibble() %>%
  group_by(station_id, country) %>%
  summarise(across(c(TOTN_dep, latitude, longitude, catchment_area, altitude, 
                     coniferous, deciduous, heathlands, lake,
                     mixed_forest, wetland, pre, tmp), mean),
            .groups = "drop") %>%
  left_join(df_station[c("station_id", "region")], by = "station_id")


slope <- slope_1 %>%
  left_join(df_meta, by = "station_id")

# slope


```


### Interactive map    
```{r make_spatial_data, echo = FALSE}
#
# Change slope data to spatial (sf)     
#

# slope_data <- dplyr::sample_n(slope, 50)   # sample 
slope_data <- slope                          # all 

#   
slope_sf <- sf::st_as_sf(
  slope_data,
  coords = c("longitude", "latitude"), 
  crs = "+proj=longlat +ellps=WGS84", 
  agr = "constant") 

ylim1 <- range(dat_annual_sel$log_NO3_madj, na.rm = TRUE)
ylim2 <- range(dat_annual_sel$TOTN_dep, na.rm = TRUE)

# names(dat_annual_sel) %>% dput()
# names(dat_annual_sel) %>% paste(collapse = ", ")

# Sequence to appear in histogram
vars <- c("log10_catchment", "altitude", 
  "coniferous", "deciduous", "heathlands", "lake", "mixed_forest", "wetland", 
  "pre", "tmp")

```

```{r create_slope plot}
#
# Create and store 'slopes' plot for all stations 
#

gg_slopes_all <- ggplot(slope_data, aes(slope_dep_vs_time, slope_no3_vs_dep)) +
  geom_point(color = "grey40")

# Test
# gg_slopes_all

```

```{r create_histograms, warning=FALSE}

#
# Create and store histogram for all stations 
#

df_hist_all <- slope_data %>%
  mutate(log10_catchment = log10(catchment_area)) %>%
  select(station_id,
         log10_catchment, altitude, coniferous, deciduous, heathlands, lake, mixed_forest,
         wetland, pre, tmp) %>%
  pivot_longer(-station_id, 
                  names_to = "variable") %>%
  mutate(variable = fct_inorder(variable))

df_hist_station <- df_hist_all %>%
  filter(station_id == df_hist_all$station_id[1])

gg_hist_all <- ggplot(df_hist_all, aes(value)) +
  geom_histogram(bins = 30) +
  facet_wrap(vars(variable), scales = "free_x", nrow = 2)

# Test
# gg_hist_all +
#   geom_vline(data = df_hist_station, aes(xintercept = value), color = "red")

  
```

```{r popup_plots_function}
#
# Make all graphs
#
make_graph <- function(i){
  df_sel <- dat_annual_sel %>%
    filter(station_id %in% slope_sf$station_id[i])
  df_slope_sel <- slope_data %>%
    filter(station_id %in% slope_sf$station_id[i])
  # Time series NO3
  g1 <- ggplot(df_sel, aes(x = year, y = log_NO3_madj)) + 
    geom_smooth(method = "lm", formula = 'y ~ x') +
    geom_point() +
    ylim(ylim1) +
    labs(title = paste(slope_sf$station_id[i], "NO3")) 
  # Time series NOTN
  g2 <- ggplot(df_sel, aes(x = year, y = TOTN_dep)) + 
    geom_smooth(method = "lm", formula = 'y ~ x') +
    geom_point() +
    ylim(ylim2) +
    labs(title = paste(slope_sf$station_id[i], "TotN deposition"))
  # Slopes, add ing a red dot for current time series  
  g3 <- gg_slopes_all +
    geom_point(data = df_slope_sel, color = "red")
  # Combine the three tow-row plots  
  gg_top <- cowplot::plot_grid(g1, g2, g3, nrow = 1)
  # Data for red vertical line on theh histograms  
  df_hist_station <- df_hist_all %>%
    filter(station_id == slope_sf$station_id[i])
  # Make histograms
  gg_bottom <- gg_hist_all +
    geom_vline(data = df_hist_station, aes(xintercept = value), color = "red")
  # Combine all plots
  cowplot::plot_grid(gg_top, gg_bottom, nrow = 2, rel_heights = c(1,1))
}

# Test
# make_graph(3)

```
```{r create_popup_plots, message=FALSE, warning=FALSE}

p <- seq_along(slope_sf$station_id) %>% purrr::map(make_graph)

```


```{r create_main_plot, fig.width=9, fig.height=9}
#
### Make main plot
#

# Classify 'slope_no3_vs_dep' -> 'slope_no3_vs_dep_class'
slope_sf <- slope_sf %>%
  mutate(slope_no3_vs_dep_class = 
           cut(slope_no3_vs_dep, breaks = c(seq(-0.05, 0.02, 0.01), 0.11)))

mapview(slope_sf, zcol = "slope_no3_vs_dep_class", popup = leafpop::popupGraph(p, width = 430, height = 400))

```